sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vladosed/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vladosed/docker-react npm run test

  ###some useless stuff
  
