sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vladosed/docker-react Dockerfile.dev .

script:
  - docker run -e CI=true vladosed/docker-react npm run test
